### PR TITLE
PR dealing with Issue #359

### PR DESCRIPTION
**Pull request by KevinEeckman**
Implemented feature as discused in issue #359

### CODE REVIEW

**Comment by johanmeijer** [comment]
@KevinEeckman. You made this changes to the master. I will commit changes to the master, only to the beta branche. I see that there are some conflicts between master and beta so this might not completely fit. 

I do understand you are using test programs (I have 2 test programs as wel, see also examples: grotttest.py which test the grottdata processing). I also have  end2end test program (using python unittest) but decided not to publish it before I had documented it. 

I will see if I can fit your changes on the beta branch.

**Comment by KevinEeckman** [comment]
Hi,

I can try to merge it to beta if it more convenient for you

I used pytest, it's similar to unittest and both should be able to run your
and my tests (I'll have a look at grotttest to see if it could be ported to
unittest/pytest as well)

**Comment by johanmeijer** [comment]
IF you want to merge it to the beta build that would be nice!

I will publish my testprogram as well. I used it to test Grottserver (basically test the communication) but can be used to test full Grott functionality.

**Comment by KevinEeckman** [comment]
Closed this pull request to master and opening a new one on Beta

**Pull request closed without merging**
