### PR TITLE
Some changes for grottserver

### PR DESCRIPTION
**Pull request by rany2**
Changes:
* [allow setting of timezone and default to UTC](https://github.com/johanmeijer/grott/commit/c85fe40324ccf12de09c1d4796dea809f08a74c5)
* [add data record forward option](https://github.com/johanmeijer/grott/commit/9c00981a0d765f6868efef0f85a596024f352ee9)
* [use getpeername at the logger reg cleanup stage](https://github.com/johanmeijer/grott/commit/7a38865f34b522d749fb6b75b729145023cc8922)
* [make read/write timeout for register configurable](https://github.com/johanmeijer/grott/pull/122/commits/e76a2e74c0037c61353bffe6b5c027719de2b2a8)
* [add mutexes for non-threadsafe send/recv](https://github.com/johanmeijer/grott/pull/122/commits/81ea67d45e761c732cf21146e8a517ab3a2b4d5d)

The third commit should fix exception spam of "transport endpoint is not connected error" when the system tries to clear a failed connection.

The fourth commit speeds up register retrieval and setting time.

### CODE REVIEW

**Comment by rany2** [comment]
I was able to reproduce https://github.com/johanmeijer/grott/files/8831866/grottserver.log_error.zip from the discussion forum about grottserver. It is fixed by https://github.com/johanmeijer/grott/pull/122/commits/7a38865f34b522d749fb6b75b729145023cc8922

**Comment by rany2** [comment]
I fixed up the mimetype so Firefox doesn't end up downloading the responses as some binary file. `text/body` isn't a valid mimetype so it considers is to be some binary file.

I added newlines at the end of all responses as well so it doesn't mess up my curl/bash.

**Comment by johanmeijer** [comment]
@rany2 Thank you for your contribution I will look at it and see of I can integrate it.
 
The settings and parameters I stil have to work on. I like to integrate it with the grott.ini because at the end I want to integrate grottserver in Grott.

I do not think that setting time to UTC by default is a good idea. By default the time on the inverter / datalogger is set to the local time (by growatt server). At least for the shinewifi/lan-s (and shinelan box). It will work with influx / grafana but not with pvpoutput or mqtt driven connections (like domoticz or home assistent) I think. 
We can make parameter which enables the possibility of setting UTC (or other timezones, but then I like to use the grott tz settings). 

The 107 file error can have multiple root causes. Sometimes you have to close the connection (otherwise it will loop) and sometimes not (and ironically it will loop then also). Some additional investigation is necessary I am afraid.  I will test your code with my test set. 

I think I can not commit al your changes but I want to integrate most of them.

**Comment by rany2** [comment]
@johanmeijer If it is of help, I could try to integrate Grottserver with Grott now and have it use .ini. My plan for the timezone is for it to respect the TZ setting, with the only different in Grottserver mode being that it will also set the timezone for the inverter.

**Comment by johanmeijer** [comment]
Thank you for offering your help. But I like to do it myself if you do not mind. I have some coding running here for it already. 
But want to integrate only if grottserver is stable enough (I do not want to make grott less trustworthy. 

Yes I know I have to use github for version management but at this moment I have my own version management outside github (that is how I started it). Maybe I start with version 3.0 with this.

**Comment by rany2** [comment]
@johanmeijer No worries, if you prefer I could close this pull request and wait for things to settle down then!

**Comment by johanmeijer** [comment]
The biggest challenge at this moment (next to the 107 errors, but we solved that almost i think) is the lousy response on the inverter commands. I am not sure if we can fixed that, seems something in the communication between the inverter and the datalogger.

**Comment by johanmeijer** [comment]
Keep on improving (thanks for that)! I am only looking for an easy way to integrate. 

Merge everything and then change your code again does not feels as the wright way to go.

**Comment by rany2** [comment]
@johanmeijer I haven't had lossy responses for register commands except on the inverter, so it seems like an issue with the dongle rather than the software itself. Datalogger responses get returned in millisecond speeds with https://github.com/johanmeijer/grott/pull/122/commits/e76a2e74c0037c61353bffe6b5c027719de2b2a8 but inverter commands still take a solid few seconds and sometimes don't return at all.

**Comment by johanmeijer** [comment]
> @johanmeijer I haven't had lossy responses for register commands except on the inverter, so it seems like an issue with the dongle rather than this software itself. Datalogger responses get returned in millisecond speeds with [e76a2e7](https://github.com/johanmeijer/grott/commit/e76a2e74c0037c61353bffe6b5c027719de2b2a8) but inverter commands still take a solid few seconds and sometimes don't return at all.

**Comment by johanmeijer** [comment]
And sometime it returns also a wrong values (mostly 0, but for some registers that is also ok). And that is bad. I can live with no response. I do not like wrong responses that I can not recognize. 

Luckily the only seems a problem with retrieving information. Setting the registers will be ok.

**Comment by rany2** [comment]
I have only set inverter commands and never retrieved them so I didn't notice. I have the same issue as you but only if I retrieve register data very quickly.

Do you have any tips on what what could be wrong?

**Comment by rany2** [comment]
Never mind, it happens regardless of the wait time. Even if you wait it happens, very strange.

**Comment by rany2** [comment]
I added https://github.com/johanmeijer/grott/pull/122/commits/357439c23d01d7a31f80f6158d505f2f68ad5968 to verify CRC16 when receiving data from process_data, seems like there are some CRC16 verification failures. Might help with the inverter commands

**Comment by rany2** [comment]
@johanmeijer Some good news. Every since I added in https://github.com/johanmeijer/grott/pull/122/commits/357439c23d01d7a31f80f6158d505f2f68ad5968 I've never been able to receive an incorrect inverter register response. 

I ran a script that checked for inverter register 1 (which I knew the value for) and it failed instead of returning incorrect value of 0. 

All responses from the HTTP API were either `no or invalid response received` or `{"value": 3}`.

**Comment by johanmeijer** [comment]
That is good news indeed. I am going to test and integrate your changes the comming days. Thanks!

**Comment by rany2** [comment]
UPDATE: I have verified that the CRC16 error checking code is indeed filtering out bad command responses. However it is not enough as after I modified my script's register retrieval interval from (10s to 0s) it started returning 0 values sometimes. 

Very perplexing...

**Comment by rany2** [comment]
Second update: I attempted to rate-limit all recv and send operations for one second by creating a custom mutex object. It also didn't help. I thought it might because I remember Growatt modbus documentation mentioned that there should be a ~1second delay (with min being 850ms)

**Comment by johanmeijer** [comment]
That is a pity. I really do not understand it. Most be a bug in the datalogger code. Although.... I think it exists with different dataloggers  (I have a wifishine-s) / inverter type combinations. 

I am going to try what happens if you specify multiple registers to read (maybe that is a solution). 

I really want to merge the things you improved but have some things that I think should be slightly different. 
Especially the UTC / TZ coding (default should be local, only utc coding can b done without timezone processing I think)  and the forwarding (needs a switch with Thue or False, that can be put in the .ini in the future) 

I am looking for a way to integrate you code and make the changes in a easy way.

**Comment by rany2** [comment]
> Especially the UTC / TZ coding (default should be local, only utc coding can b done without timezone processing I think)

That should be an easy fix. I could implement it if you prefer.

> the forwarding (needs a switch with Thue or False, that can be put in the .ini in the future)

This is already possible. Just make the forwardata variable an empty tuple or False

**Comment by rany2** [comment]
> @rany2 correct:
> 
> Minimum CMD period (RS485 Time out): 850ms. Wait for minimum 850ms to send a new CMD after last CMD. Suggestion is 1s;

It doesn't seem to have an effect for ShineWifi dongle. I think it's just a bug with the dongle. I will try to get the inverter registers from the Growatt website to see if I could trigger this bug from there. If so, then this must be an programming error with the dongle.

**Comment by rany2** [comment]
Great news. This error happens from Growatt's server.growatt.com web interface as well. This is not an issue with growattserver1 @johanmeijer

**Comment by rany2** [comment]
@johanmeijer I thought that might be the case as well but it is not. I tried to increase the data reporting interval from 0.1 minute to 1000 minutes to decrease the communication between the inverter and data logger as much as possible. 

Even when I sent the inverter register request when there was absolutely radio silence it still sometimes responded with 0 values.

**Comment by johanmeijer** [comment]
Hmm slowly I start to think we have to accept this behaviour.

**Comment by rany2** [comment]
Sometimes it works perfectly and sometimes it doesn't. Like right now it is working consistently and replying the correct value immediately but I haven't made any changes/fixes, it's an extremely strange behaviour

**Comment by rany2** [comment]
https://github.com/johanmeijer/grott/pull/122/commits/f8409f765987532c8638970d47c5f45a84cef5bd didn't seem to help, I'll just accept it. Too bad we can't be better than growatt itself... for now

**Comment by rany2** [comment]
I've continued my changes in the "fork" branch because I wanted to have grottserver and grott integrated already. I didn't want to keep needing to run both grottproxy and grottserver at once.

I've fixed your UTC, forwarding complaints, etc there. Sorry to have to move here: https://github.com/rany2/grott-1/tree/fork

**Comment by johanmeijer** [comment]
OK. I do understand and appreciate your enthusiasm. I can and want not to keep up with the speed of your changes (have other things to do as well).

 I started grott a couple years ago and put a lot off effort in it. It works rather fine  and I will improve it at my own speed and keeping it working for the hundreds off people already using it (including the docker versions).

Succes with your fork. I will use the changes you made and implement it in the next versions of Grott.

**Comment by rany2** [comment]
@johanmeijer I could wait, the fork is just temporary until grottserver becomes officially stable and integrated. I just released my changes in case you find it useful. No rush :)

**Comment by rany2** [comment]
> And sometime it returns also a wrong values (mostly 0, but for some registers that is also ok). And that is bad. I can live with no response. I do not like wrong responses that I can not recognize.
> 
> Luckily the only seems a problem with retrieving information. Setting the registers will be ok.

@johanmeijer  Just a heads up but I managed to solve it by updating the firmware from Growatt's website. This was a bug in the datalogger. Now instead of returning zeros it returns a value which is beyond the range of possible values (something like 2^17)

**Comment by johanmeijer** [comment]
@rany that would be nice. I will look if there is also update for my inverter (shinewifi-s).

**Comment by johanmeijer** [comment]
@rany2 

Yes there was a upgrade for me as well! I went from 1.7.7.7 to 3.0.0.2. The reaction to the inverter commands seems to be more responsive and I do not have seen any "false"( = unexpected 0) any more. 

Thanks for the tip!

**Comment by rany2** [comment]
Excellent! :)

**Pull request closed without merging**
