### PR TITLE
Align library with HA naming convention

### PR DESCRIPTION
**Pull request by bvweerd**
Align library with HA naming conventions, see https://developers.home-assistant.io/docs/core/entity/#entity-naming and change in HA 2023.8 home-assistant/core#95159

### CODE REVIEW

**Comment by johanmeijer** [comment]
I am not sure if you have to do anything in HA (like changing Graphics, saving history etc) and I  am not the creator and tester/user of the HA extension but maybe it might be better to create v2 of the extension (e.g grottha2.py) so anyone can choose when to move to the new naming convention?

**Comment by bvweerd** [comment]
the HA user will not have to re-configure anything in HA. What will change is the default visible name of the entity.

Instead of e.g. "RAL34536 Phase 1 current" the default name will be "Phase 1 current". 
new_naming

Migrating to the new naming will not result in e.g. any broken automations, since the entity id will remain the same.

**Comment by johanmeijer** [comment]
Ok sounds good. @egguy do you agree with this change?

**Comment by egguy** [comment]
This has been implemented in MR #412 with other bug fix

**Pull request merged**
