### PR TITLE
HA extension 0.0.7

### PR DESCRIPTION
**Pull request by egguy**
Hi,
After a bit of time, this new update of the extension. 

The new extension also implement the required change for HA and the MQTT change.

Multiple bugs have been corrected.
  - Corrected a bug when creating the configuration
  - Add QoS 1 to reduce the possibility of lost message.
  - Updated Total work time unit.
  - Add support for setting the retain flag
  - Add more configurations for measures
  - Refactored code for measures
  - Implemented the new changes for HA MQTT

### CODE REVIEW

**Comment by egguy** [comment]
Also, how can I make the release and update of the integration a bit smoother?

 Should I publish it as a package you can install by pip. So the maintenance and integration can be done without disruption your release process?

**Comment by johanmeijer** [comment]
I see this at this moment as "your" extension. I will accept all changes you made to it ;)

**Comment by egguy** [comment]
Hi, I have transformed the extension as a python library you can install with a `pip install`. You cam find it here: https://pypi.org/project/grott-ha-plugin/

This will reduce your burden on merging, maintenance and allows me to iterate faster on the version.

Can I suggest people to switch to  use this instead of using the file stored in the extension folder?

**Comment by johanmeijer** [comment]
Nice! 

@egguy is it an idea to remove the extension from the sample library and update the documentation (wiki) for this? 

Maybe we can do this with the next release (grott 2.9 or 3.0).

**Pull request merged**
