### PR TITLE
Proxy server - poll

### PR DESCRIPTION
**Pull request by githubDante**
Event based operation when Grott is used in proxy mode The data will be read from the socket as soon as it's available.

* More OOP approach for handling of the client <-> server connections (ProxyPair class) 
* The Conf class added & used as a Proxy class attribute 
* Added type hints for the changed sections

This is a resubmission of a pull request previously sent to the master branch. Adapted to the code in the Beta.

### CODE REVIEW

**Comment by rany2** [comment]
You may want to have a look at https://github.com/rany2/grott/blob/master/grottproxy.py and take inspiration for this PR. Should be a lot less CPU intensive than this and easier to read/understand.

**Comment by githubDante** [comment]
> Edit: (When I first attempted an approach similar to this, it was using up about 4-5% of CPU doing basically nothing. This keeps things at a nice 0%)
Yep, basically it waits for data all the time without any loops :sunglasses:

**Comment by githubDante** [comment]
@rany2 I had time to look at the code you pointed. It's nicely structured, 
but really overcomplicated for the task. The proxy needs to be fast
on receiving/forwarding the data from/to both ends. All those queues and threads are
not needed.

I think the other improvements (except for the poll implementation) which can be done are:
 - faster packet decoder see the pull request from @egguy (#199) and his byte decoder
 - data processing (sending to MQTT & the other backends) in sub-process or in separate thread.
  Yes, starting a sub-process is little bit expensive, but the GIL will be avoided with it, 
 which in turn will allow the proxy to process/forward even more packets in both
 directions if this is needed by anyone. 

The aim of this pull request is better proxy implementation with minimal code
changes + integration with the existing code.

**Comment by johanmeijer** [comment]
Hey Guys, nice you are discussion about my software and my hobby project. 

I do not want to be too cheeky and really like advice to improve the code (as long as I can process and learn from it), but **I** decide what is going to be changed in Grott. 

A good and stable working Grott that is not using to much resources is what I want. Performance is not really an issue. The inverter / datalogger combination is slow we can not change that (although it is a ESP8266 based datalogger, so.....  ;) 

Big code and functional changes I will not adopt. It is my code and I like to understand how it works and be able to maintain (and test) it. 
I have a test set (automatic testware) with a bulk of data from different inverter / dataloggers types collected the last years. Normally I use this to test before publish.  We already violating this basis software development principle (at least mine).

Next to it I have ideas how the proceed with Grott and how I want to change it in a evolutionary way in the future. 

To be honest I think I created a functional good working tool (used by a lot of people around the world), working for most Growatt inverter /datalogger combinations and with capabilities to adopt fast new things (e.g. layouts ad extensions) without the need for changing the code. 

You can help me with improving Grott (you are more then welcome to advice me on that) but the main thing for me is keeping pleasure in the project (that I already run for over 4 years) an do things at my own pace!

Read also: https://github.com/johanmeijer/grott/wiki/@Statement-of-use-and-limitations

**Pull request closed without merging**
