### PR TITLE
PvOut limit

### PR DESCRIPTION
**Pull request by githubDante**
Configurable (via grott.ini) PvOut upload limit.
Requested in #56 & #197

### CODE REVIEW

**Comment by johanmeijer** [comment]
@githubDante Oops you add this ti the master (and I merged it). 

The idea was that the master is frozen and the updates are done to the beta. 

I wil try to also apply it to the Beta (2.7)

**Comment by johanmeijer** [comment]
I revert this one. Sorry!

**Comment by johanmeijer** [comment]
I tried to re-fit at the beta branche but that seems not to be possible. We have to re-code it again (with the Beta branche as base).

**Comment by githubDante** [comment]
OK. Sorry for the inconvenience. GitHub by default pulls only the master branch on fork, and currently I have only the master tree.  I will have to delete it (obviously) and to create a new pull requests against the beta.

**Pull request merged**
