### PR TITLE
[grottext] add full url

### LINKED ISSUE #354: Add 'path' parameter to grott.ini for grottext.py
Many thanks for your work in developing the Grott application! :)

I am working on integrating Growatt inverters into OpenHAB by means of your Grott application.

The integration will use 'grottext.py' to POST the Grott data to a custom endpoint the OpenHAB main server. The endpoint will be something like `http://<openhab-uip-address>:8080/growatt`.

Currently the 'grottext.py' configuration only has entries for `ip` and `port`, but to reach the OpenHab endpoint we will need to add a `path` entry (like '/growatt') to the configuration.

I hereby request for you to add such a `path` configuration entry. :)

Note it is also possible that some users will have set their OpenHAB system to require `https` rather than `http` so it might also be necessary to add a `protocol` configuration entry as well.

### PR DESCRIPTION
**Pull request by andrewfg**
Fixes #354 

I never wrote any python before, so this is my first attempt. :)

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by rany2** [comment]
This will fail with KeyError if url is not defined, something that works would be:

```
    if "url" in conf.extvar:
        url = conf.extvar["url"]
```

also would be a good idea to add the old `url = "http://" + conf.extvar["ip"] + ":" + str(conf.extvar["port"]) ` assignment in the else clause, so finally (in order to not require ip and port to defined if "url" was already defined):

```
    if "url" in conf.extvar:
        url = conf.extvar["url"]
    else:
        url = "http://" + conf.extvar["ip"] + ":" + str(conf.extvar["port"]) 
```

**Comment by andrewfg** [comment]
> This will fail with KeyError if url is not defined

@rany2 many thanks for the info; I never wrote any Python before yesterday!

**Comment by andrewfg** [comment]
@johanmeijer it seems that this PR WAS merged into into version 2.7.8 yet it seems that master branch version 2.8.3 does NOT include that change anymore. Could you please re-merge it?

https://community.openhab.org/t/growatt-solar-inverter-binding-4-0-0-4-2-0/150600/4?u=andrewfg

**Comment by johanmeijer** [comment]
Done

**Pull request merged**
