### PR TITLE
Do not run the Grott service as root

### PR DESCRIPTION
**Pull request by phavekes**
In proxy-mode, no root access is needed

### CODE REVIEW

**Comment by johanmeijer** [comment]
I agree that it is better not to run as Root. But Pi is also not the best option while it not only running at @ PI but also at Nas systems and other x86 servers without the PI user.  

Probably the best will be a grott user but then we have to make config instructions for that.

**Comment by rany2** [comment]
@johanmeijer The systemd unit already assumes grott is installed in /home/pi/ so in its current state it considers that the pi user exists. I think currently this PR is fine, but in the future it might be better to have the unit file use bogus values to be filled by the user like:

* /home/pi -> /path/to/grott
* root -> user_you_want_to_run_grott_as
* etc

**Comment by johanmeijer** [comment]
You use the Matser Branche as base. I do not want to updat the Master branch anymore. 
I will try to move the PR to the Beta branche

**Comment by johanmeijer** [comment]
Nope that is not working. To much changes would be made. We have to redo this for the Beta. 

I will not merge this one with the Master!

**Comment by phavekes** [comment]
I'll rebase the PR

**Pull request closed without merging**
